// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public interface ChainTranscationResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ChainTranscationRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string BatchidReq = 1;</code>
   */
  java.lang.String getBatchidReq();
  /**
   * <code>string BatchidReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatchidReqBytes();

  /**
   * <code>bool IsSuccess = 2;</code>
   */
  boolean getIsSuccess();
}
