// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

/**
 * <pre>
 *链请求交易体
 * </pre>
 *
 * Protobuf type {@code server.ChainTranscationReq}
 */
public  final class ChainTranscationReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:server.ChainTranscationReq)
    ChainTranscationReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChainTranscationReq.newBuilder() to construct.
  private ChainTranscationReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChainTranscationReq() {
    batchidReq_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChainTranscationReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            batchidReq_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              txsReq_ = com.google.protobuf.MapField.newMapField(
                  TxsReqDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            txsReq__ = input.readMessage(
                TxsReqDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            txsReq_.getMutableMap().put(
                txsReq__.getKey(), txsReq__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JavaTranscationServerProto.internal_static_server_ChainTranscationReq_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetTxsReq();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JavaTranscationServerProto.internal_static_server_ChainTranscationReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChainTranscationReq.class, ChainTranscationReq.Builder.class);
  }

  private int bitField0_;
  public static final int BATCHIDREQ_FIELD_NUMBER = 1;
  private volatile java.lang.Object batchidReq_;
  /**
   * <pre>
   * 批id
   * </pre>
   *
   * <code>string BatchidReq = 1;</code>
   */
  public java.lang.String getBatchidReq() {
    java.lang.Object ref = batchidReq_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchidReq_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 批id
   * </pre>
   *
   * <code>string BatchidReq = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBatchidReqBytes() {
    java.lang.Object ref = batchidReq_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchidReq_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TXSREQ_FIELD_NUMBER = 2;
  private static final class TxsReqDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                JavaTranscationServerProto.internal_static_server_ChainTranscationReq_TxsReqEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> txsReq_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTxsReq() {
    if (txsReq_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TxsReqDefaultEntryHolder.defaultEntry);
    }
    return txsReq_;
  }

  public int getTxsReqCount() {
    return internalGetTxsReq().getMap().size();
  }
  /**
   * <pre>
   * 批交易集合
   * </pre>
   *
   * <code>map&lt;string, string&gt; TxsReq = 2;</code>
   */

  public boolean containsTxsReq(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetTxsReq().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTxsReqMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTxsReq() {
    return getTxsReqMap();
  }
  /**
   * <pre>
   * 批交易集合
   * </pre>
   *
   * <code>map&lt;string, string&gt; TxsReq = 2;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getTxsReqMap() {
    return internalGetTxsReq().getMap();
  }
  /**
   * <pre>
   * 批交易集合
   * </pre>
   *
   * <code>map&lt;string, string&gt; TxsReq = 2;</code>
   */

  public java.lang.String getTxsReqOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTxsReq().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 批交易集合
   * </pre>
   *
   * <code>map&lt;string, string&gt; TxsReq = 2;</code>
   */

  public java.lang.String getTxsReqOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTxsReq().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBatchidReqBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, batchidReq_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTxsReq(),
        TxsReqDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBatchidReqBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, batchidReq_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTxsReq().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      txsReq__ = TxsReqDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, txsReq__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChainTranscationReq)) {
      return super.equals(obj);
    }
    ChainTranscationReq other = (ChainTranscationReq) obj;

    boolean result = true;
    result = result && getBatchidReq()
        .equals(other.getBatchidReq());
    result = result && internalGetTxsReq().equals(
        other.internalGetTxsReq());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATCHIDREQ_FIELD_NUMBER;
    hash = (53 * hash) + getBatchidReq().hashCode();
    if (!internalGetTxsReq().getMap().isEmpty()) {
      hash = (37 * hash) + TXSREQ_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTxsReq().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChainTranscationReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChainTranscationReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChainTranscationReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChainTranscationReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChainTranscationReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChainTranscationReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChainTranscationReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChainTranscationReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChainTranscationReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChainTranscationReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChainTranscationReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChainTranscationReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChainTranscationReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *链请求交易体
   * </pre>
   *
   * Protobuf type {@code server.ChainTranscationReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ChainTranscationReq)
          ChainTranscationReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JavaTranscationServerProto.internal_static_server_ChainTranscationReq_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetTxsReq();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableTxsReq();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JavaTranscationServerProto.internal_static_server_ChainTranscationReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChainTranscationReq.class, ChainTranscationReq.Builder.class);
    }

    // Construct using serverproto.ChainTranscationReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      batchidReq_ = "";

      internalGetMutableTxsReq().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JavaTranscationServerProto.internal_static_server_ChainTranscationReq_descriptor;
    }

    @java.lang.Override
    public ChainTranscationReq getDefaultInstanceForType() {
      return ChainTranscationReq.getDefaultInstance();
    }

    @java.lang.Override
    public ChainTranscationReq build() {
      ChainTranscationReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ChainTranscationReq buildPartial() {
      ChainTranscationReq result = new ChainTranscationReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.batchidReq_ = batchidReq_;
      result.txsReq_ = internalGetTxsReq();
      result.txsReq_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChainTranscationReq) {
        return mergeFrom((ChainTranscationReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChainTranscationReq other) {
      if (other == ChainTranscationReq.getDefaultInstance()) return this;
      if (!other.getBatchidReq().isEmpty()) {
        batchidReq_ = other.batchidReq_;
        onChanged();
      }
      internalGetMutableTxsReq().mergeFrom(
          other.internalGetTxsReq());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChainTranscationReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChainTranscationReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object batchidReq_ = "";
    /**
     * <pre>
     * 批id
     * </pre>
     *
     * <code>string BatchidReq = 1;</code>
     */
    public java.lang.String getBatchidReq() {
      java.lang.Object ref = batchidReq_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchidReq_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 批id
     * </pre>
     *
     * <code>string BatchidReq = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBatchidReqBytes() {
      java.lang.Object ref = batchidReq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchidReq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 批id
     * </pre>
     *
     * <code>string BatchidReq = 1;</code>
     */
    public Builder setBatchidReq(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batchidReq_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 批id
     * </pre>
     *
     * <code>string BatchidReq = 1;</code>
     */
    public Builder clearBatchidReq() {
      
      batchidReq_ = getDefaultInstance().getBatchidReq();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 批id
     * </pre>
     *
     * <code>string BatchidReq = 1;</code>
     */
    public Builder setBatchidReqBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batchidReq_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> txsReq_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTxsReq() {
      if (txsReq_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TxsReqDefaultEntryHolder.defaultEntry);
      }
      return txsReq_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableTxsReq() {
      onChanged();;
      if (txsReq_ == null) {
        txsReq_ = com.google.protobuf.MapField.newMapField(
            TxsReqDefaultEntryHolder.defaultEntry);
      }
      if (!txsReq_.isMutable()) {
        txsReq_ = txsReq_.copy();
      }
      return txsReq_;
    }

    public int getTxsReqCount() {
      return internalGetTxsReq().getMap().size();
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */

    public boolean containsTxsReq(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTxsReq().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTxsReqMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTxsReq() {
      return getTxsReqMap();
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTxsReqMap() {
      return internalGetTxsReq().getMap();
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */

    public java.lang.String getTxsReqOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTxsReq().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */

    public java.lang.String getTxsReqOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTxsReq().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTxsReq() {
      internalGetMutableTxsReq().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */

    public Builder removeTxsReq(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTxsReq().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableTxsReq() {
      return internalGetMutableTxsReq().getMutableMap();
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */
    public Builder putTxsReq(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTxsReq().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * 批交易集合
     * </pre>
     *
     * <code>map&lt;string, string&gt; TxsReq = 2;</code>
     */

    public Builder putAllTxsReq(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTxsReq().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:server.ChainTranscationReq)
  }

  // @@protoc_insertion_point(class_scope:server.ChainTranscationReq)
  private static final ChainTranscationReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChainTranscationReq();
  }

  public static ChainTranscationReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChainTranscationReq>
      PARSER = new com.google.protobuf.AbstractParser<ChainTranscationReq>() {
    @java.lang.Override
    public ChainTranscationReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChainTranscationReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChainTranscationReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChainTranscationReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ChainTranscationReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

