// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public interface ClientTransactionReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientTransactionReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string TxidReq = 1;</code>
   */
  java.lang.String getTxidReq();
  /**
   * <code>string TxidReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getTxidReqBytes();
}
