// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public interface ClientTransactionJavaResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientTransactionJavaRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string TxidRes = 1;</code>
   */
  java.lang.String getTxidRes();
  /**
   * <code>string TxidRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getTxidResBytes();

  /**
   * <code>string IsReceivedRes = 2;</code>
   */
  java.lang.String getIsReceivedRes();
  /**
   * <code>string IsReceivedRes = 2;</code>
   */
  com.google.protobuf.ByteString
      getIsReceivedResBytes();
}
