// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

/**
 * <pre>
 *服务端请求交易返回值
 * </pre>
 *
 * Protobuf type {@code server.ClientTransactionRes}
 */
public  final class ClientTransactionRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:server.ClientTransactionRes)
    ClientTransactionResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientTransactionRes.newBuilder() to construct.
  private ClientTransactionRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientTransactionRes() {
    txidRes_ = "";
    codeRes_ = "";
    messageRes_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientTransactionRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            txidRes_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            codeRes_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            messageRes_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JavaTranscationServerProto.internal_static_server_ClientTransactionRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JavaTranscationServerProto.internal_static_server_ClientTransactionRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ClientTransactionRes.class, ClientTransactionRes.Builder.class);
  }

  public static final int TXIDRES_FIELD_NUMBER = 1;
  private volatile java.lang.Object txidRes_;
  /**
   * <code>string TxidRes = 1;</code>
   */
  public java.lang.String getTxidRes() {
    java.lang.Object ref = txidRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txidRes_ = s;
      return s;
    }
  }
  /**
   * <code>string TxidRes = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTxidResBytes() {
    java.lang.Object ref = txidRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txidRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODERES_FIELD_NUMBER = 2;
  private volatile java.lang.Object codeRes_;
  /**
   * <code>string CodeRes = 2;</code>
   */
  public java.lang.String getCodeRes() {
    java.lang.Object ref = codeRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codeRes_ = s;
      return s;
    }
  }
  /**
   * <code>string CodeRes = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCodeResBytes() {
    java.lang.Object ref = codeRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codeRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGERES_FIELD_NUMBER = 3;
  private volatile java.lang.Object messageRes_;
  /**
   * <code>string MessageRes = 3;</code>
   */
  public java.lang.String getMessageRes() {
    java.lang.Object ref = messageRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageRes_ = s;
      return s;
    }
  }
  /**
   * <code>string MessageRes = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageResBytes() {
    java.lang.Object ref = messageRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTxidResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txidRes_);
    }
    if (!getCodeResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codeRes_);
    }
    if (!getMessageResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageRes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTxidResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txidRes_);
    }
    if (!getCodeResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codeRes_);
    }
    if (!getMessageResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageRes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ClientTransactionRes)) {
      return super.equals(obj);
    }
    ClientTransactionRes other = (ClientTransactionRes) obj;

    boolean result = true;
    result = result && getTxidRes()
        .equals(other.getTxidRes());
    result = result && getCodeRes()
        .equals(other.getCodeRes());
    result = result && getMessageRes()
        .equals(other.getMessageRes());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TXIDRES_FIELD_NUMBER;
    hash = (53 * hash) + getTxidRes().hashCode();
    hash = (37 * hash) + CODERES_FIELD_NUMBER;
    hash = (53 * hash) + getCodeRes().hashCode();
    hash = (37 * hash) + MESSAGERES_FIELD_NUMBER;
    hash = (53 * hash) + getMessageRes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ClientTransactionRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientTransactionRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientTransactionRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientTransactionRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientTransactionRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientTransactionRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientTransactionRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ClientTransactionRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ClientTransactionRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ClientTransactionRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ClientTransactionRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ClientTransactionRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ClientTransactionRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *服务端请求交易返回值
   * </pre>
   *
   * Protobuf type {@code server.ClientTransactionRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ClientTransactionRes)
          ClientTransactionResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JavaTranscationServerProto.internal_static_server_ClientTransactionRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JavaTranscationServerProto.internal_static_server_ClientTransactionRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientTransactionRes.class, ClientTransactionRes.Builder.class);
    }

    // Construct using serverproto.ClientTransactionRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      txidRes_ = "";

      codeRes_ = "";

      messageRes_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JavaTranscationServerProto.internal_static_server_ClientTransactionRes_descriptor;
    }

    @java.lang.Override
    public ClientTransactionRes getDefaultInstanceForType() {
      return ClientTransactionRes.getDefaultInstance();
    }

    @java.lang.Override
    public ClientTransactionRes build() {
      ClientTransactionRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ClientTransactionRes buildPartial() {
      ClientTransactionRes result = new ClientTransactionRes(this);
      result.txidRes_ = txidRes_;
      result.codeRes_ = codeRes_;
      result.messageRes_ = messageRes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ClientTransactionRes) {
        return mergeFrom((ClientTransactionRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ClientTransactionRes other) {
      if (other == ClientTransactionRes.getDefaultInstance()) return this;
      if (!other.getTxidRes().isEmpty()) {
        txidRes_ = other.txidRes_;
        onChanged();
      }
      if (!other.getCodeRes().isEmpty()) {
        codeRes_ = other.codeRes_;
        onChanged();
      }
      if (!other.getMessageRes().isEmpty()) {
        messageRes_ = other.messageRes_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ClientTransactionRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ClientTransactionRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object txidRes_ = "";
    /**
     * <code>string TxidRes = 1;</code>
     */
    public java.lang.String getTxidRes() {
      java.lang.Object ref = txidRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txidRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTxidResBytes() {
      java.lang.Object ref = txidRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txidRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public Builder setTxidRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      txidRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public Builder clearTxidRes() {
      
      txidRes_ = getDefaultInstance().getTxidRes();
      onChanged();
      return this;
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public Builder setTxidResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      txidRes_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object codeRes_ = "";
    /**
     * <code>string CodeRes = 2;</code>
     */
    public java.lang.String getCodeRes() {
      java.lang.Object ref = codeRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codeRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string CodeRes = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeResBytes() {
      java.lang.Object ref = codeRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codeRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string CodeRes = 2;</code>
     */
    public Builder setCodeRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codeRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string CodeRes = 2;</code>
     */
    public Builder clearCodeRes() {
      
      codeRes_ = getDefaultInstance().getCodeRes();
      onChanged();
      return this;
    }
    /**
     * <code>string CodeRes = 2;</code>
     */
    public Builder setCodeResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codeRes_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object messageRes_ = "";
    /**
     * <code>string MessageRes = 3;</code>
     */
    public java.lang.String getMessageRes() {
      java.lang.Object ref = messageRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string MessageRes = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageResBytes() {
      java.lang.Object ref = messageRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string MessageRes = 3;</code>
     */
    public Builder setMessageRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string MessageRes = 3;</code>
     */
    public Builder clearMessageRes() {
      
      messageRes_ = getDefaultInstance().getMessageRes();
      onChanged();
      return this;
    }
    /**
     * <code>string MessageRes = 3;</code>
     */
    public Builder setMessageResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageRes_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:server.ClientTransactionRes)
  }

  // @@protoc_insertion_point(class_scope:server.ClientTransactionRes)
  private static final ClientTransactionRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ClientTransactionRes();
  }

  public static ClientTransactionRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientTransactionRes>
      PARSER = new com.google.protobuf.AbstractParser<ClientTransactionRes>() {
    @java.lang.Override
    public ClientTransactionRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientTransactionRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientTransactionRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientTransactionRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ClientTransactionRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

