// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public interface ClientTransactionResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientTransactionRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string TxidRes = 1;</code>
   */
  java.lang.String getTxidRes();
  /**
   * <code>string TxidRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getTxidResBytes();

  /**
   * <code>string CodeRes = 2;</code>
   */
  java.lang.String getCodeRes();
  /**
   * <code>string CodeRes = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeResBytes();

  /**
   * <code>string MessageRes = 3;</code>
   */
  java.lang.String getMessageRes();
  /**
   * <code>string MessageRes = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageResBytes();
}
