// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public interface ClientRegisterAddressReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientRegisterAddressReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ip
   * </pre>
   *
   * <code>string AddRessIpReq = 1;</code>
   */
  java.lang.String getAddRessIpReq();
  /**
   * <pre>
   *ip
   * </pre>
   *
   * <code>string AddRessIpReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddRessIpReqBytes();

  /**
   * <pre>
   *端口
   * </pre>
   *
   * <code>string AddRessPortReq = 2;</code>
   */
  java.lang.String getAddRessPortReq();
  /**
   * <pre>
   *端口
   * </pre>
   *
   * <code>string AddRessPortReq = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddRessPortReqBytes();

  /**
   * <pre>
   * 备注
   * </pre>
   *
   * <code>string RemarkReq = 3;</code>
   */
  java.lang.String getRemarkReq();
  /**
   * <pre>
   * 备注
   * </pre>
   *
   * <code>string RemarkReq = 3;</code>
   */
  com.google.protobuf.ByteString
      getRemarkReqBytes();
}
