// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public interface ClientRegisterAddressResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientRegisterAddressRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 成功信息
   * </pre>
   *
   * <code>string MessageRes = 1;</code>
   */
  java.lang.String getMessageRes();
  /**
   * <pre>
   * 成功信息
   * </pre>
   *
   * <code>string MessageRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageResBytes();

  /**
   * <pre>
   *注册成功标志
   * </pre>
   *
   * <code>bool IsSuccess = 2;</code>
   */
  boolean getIsSuccess();

  /**
   * <pre>
   *成功
   * </pre>
   *
   * <code>string MessageIDRes = 3;</code>
   */
  java.lang.String getMessageIDRes();
  /**
   * <pre>
   *成功
   * </pre>
   *
   * <code>string MessageIDRes = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageIDResBytes();
}
