// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

/**
 * <pre>
 *服务端注册地址返回值
 * </pre>
 *
 * Protobuf type {@code server.ClientRegisterAddressRes}
 */
public  final class ClientRegisterAddressRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:server.ClientRegisterAddressRes)
    ClientRegisterAddressResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientRegisterAddressRes.newBuilder() to construct.
  private ClientRegisterAddressRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientRegisterAddressRes() {
    messageRes_ = "";
    isSuccess_ = false;
    messageIDRes_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientRegisterAddressRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            messageRes_ = s;
            break;
          }
          case 16: {

            isSuccess_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            messageIDRes_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JavaTranscationServerProto.internal_static_server_ClientRegisterAddressRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JavaTranscationServerProto.internal_static_server_ClientRegisterAddressRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ClientRegisterAddressRes.class, ClientRegisterAddressRes.Builder.class);
  }

  public static final int MESSAGERES_FIELD_NUMBER = 1;
  private volatile java.lang.Object messageRes_;
  /**
   * <pre>
   * 成功信息
   * </pre>
   *
   * <code>string MessageRes = 1;</code>
   */
  public java.lang.String getMessageRes() {
    java.lang.Object ref = messageRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageRes_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 成功信息
   * </pre>
   *
   * <code>string MessageRes = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageResBytes() {
    java.lang.Object ref = messageRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSUCCESS_FIELD_NUMBER = 2;
  private boolean isSuccess_;
  /**
   * <pre>
   *注册成功标志
   * </pre>
   *
   * <code>bool IsSuccess = 2;</code>
   */
  public boolean getIsSuccess() {
    return isSuccess_;
  }

  public static final int MESSAGEIDRES_FIELD_NUMBER = 3;
  private volatile java.lang.Object messageIDRes_;
  /**
   * <pre>
   *成功
   * </pre>
   *
   * <code>string MessageIDRes = 3;</code>
   */
  public java.lang.String getMessageIDRes() {
    java.lang.Object ref = messageIDRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageIDRes_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *成功
   * </pre>
   *
   * <code>string MessageIDRes = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageIDResBytes() {
    java.lang.Object ref = messageIDRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageIDRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageRes_);
    }
    if (isSuccess_ != false) {
      output.writeBool(2, isSuccess_);
    }
    if (!getMessageIDResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageIDRes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageRes_);
    }
    if (isSuccess_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isSuccess_);
    }
    if (!getMessageIDResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageIDRes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ClientRegisterAddressRes)) {
      return super.equals(obj);
    }
    ClientRegisterAddressRes other = (ClientRegisterAddressRes) obj;

    boolean result = true;
    result = result && getMessageRes()
        .equals(other.getMessageRes());
    result = result && (getIsSuccess()
        == other.getIsSuccess());
    result = result && getMessageIDRes()
        .equals(other.getMessageIDRes());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGERES_FIELD_NUMBER;
    hash = (53 * hash) + getMessageRes().hashCode();
    hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuccess());
    hash = (37 * hash) + MESSAGEIDRES_FIELD_NUMBER;
    hash = (53 * hash) + getMessageIDRes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ClientRegisterAddressRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientRegisterAddressRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientRegisterAddressRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientRegisterAddressRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientRegisterAddressRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientRegisterAddressRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientRegisterAddressRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ClientRegisterAddressRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ClientRegisterAddressRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ClientRegisterAddressRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ClientRegisterAddressRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ClientRegisterAddressRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ClientRegisterAddressRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *服务端注册地址返回值
   * </pre>
   *
   * Protobuf type {@code server.ClientRegisterAddressRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ClientRegisterAddressRes)
          ClientRegisterAddressResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JavaTranscationServerProto.internal_static_server_ClientRegisterAddressRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JavaTranscationServerProto.internal_static_server_ClientRegisterAddressRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientRegisterAddressRes.class, ClientRegisterAddressRes.Builder.class);
    }

    // Construct using serverproto.ClientRegisterAddressRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageRes_ = "";

      isSuccess_ = false;

      messageIDRes_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JavaTranscationServerProto.internal_static_server_ClientRegisterAddressRes_descriptor;
    }

    @java.lang.Override
    public ClientRegisterAddressRes getDefaultInstanceForType() {
      return ClientRegisterAddressRes.getDefaultInstance();
    }

    @java.lang.Override
    public ClientRegisterAddressRes build() {
      ClientRegisterAddressRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ClientRegisterAddressRes buildPartial() {
      ClientRegisterAddressRes result = new ClientRegisterAddressRes(this);
      result.messageRes_ = messageRes_;
      result.isSuccess_ = isSuccess_;
      result.messageIDRes_ = messageIDRes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ClientRegisterAddressRes) {
        return mergeFrom((ClientRegisterAddressRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ClientRegisterAddressRes other) {
      if (other == ClientRegisterAddressRes.getDefaultInstance()) return this;
      if (!other.getMessageRes().isEmpty()) {
        messageRes_ = other.messageRes_;
        onChanged();
      }
      if (other.getIsSuccess() != false) {
        setIsSuccess(other.getIsSuccess());
      }
      if (!other.getMessageIDRes().isEmpty()) {
        messageIDRes_ = other.messageIDRes_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ClientRegisterAddressRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ClientRegisterAddressRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object messageRes_ = "";
    /**
     * <pre>
     * 成功信息
     * </pre>
     *
     * <code>string MessageRes = 1;</code>
     */
    public java.lang.String getMessageRes() {
      java.lang.Object ref = messageRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 成功信息
     * </pre>
     *
     * <code>string MessageRes = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageResBytes() {
      java.lang.Object ref = messageRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 成功信息
     * </pre>
     *
     * <code>string MessageRes = 1;</code>
     */
    public Builder setMessageRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成功信息
     * </pre>
     *
     * <code>string MessageRes = 1;</code>
     */
    public Builder clearMessageRes() {
      
      messageRes_ = getDefaultInstance().getMessageRes();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 成功信息
     * </pre>
     *
     * <code>string MessageRes = 1;</code>
     */
    public Builder setMessageResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageRes_ = value;
      onChanged();
      return this;
    }

    private boolean isSuccess_ ;
    /**
     * <pre>
     *注册成功标志
     * </pre>
     *
     * <code>bool IsSuccess = 2;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }
    /**
     * <pre>
     *注册成功标志
     * </pre>
     *
     * <code>bool IsSuccess = 2;</code>
     */
    public Builder setIsSuccess(boolean value) {
      
      isSuccess_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *注册成功标志
     * </pre>
     *
     * <code>bool IsSuccess = 2;</code>
     */
    public Builder clearIsSuccess() {
      
      isSuccess_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object messageIDRes_ = "";
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>string MessageIDRes = 3;</code>
     */
    public java.lang.String getMessageIDRes() {
      java.lang.Object ref = messageIDRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageIDRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>string MessageIDRes = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIDResBytes() {
      java.lang.Object ref = messageIDRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageIDRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>string MessageIDRes = 3;</code>
     */
    public Builder setMessageIDRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageIDRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>string MessageIDRes = 3;</code>
     */
    public Builder clearMessageIDRes() {
      
      messageIDRes_ = getDefaultInstance().getMessageIDRes();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>string MessageIDRes = 3;</code>
     */
    public Builder setMessageIDResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageIDRes_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:server.ClientRegisterAddressRes)
  }

  // @@protoc_insertion_point(class_scope:server.ClientRegisterAddressRes)
  private static final ClientRegisterAddressRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ClientRegisterAddressRes();
  }

  public static ClientRegisterAddressRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientRegisterAddressRes>
      PARSER = new com.google.protobuf.AbstractParser<ClientRegisterAddressRes>() {
    @java.lang.Override
    public ClientRegisterAddressRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientRegisterAddressRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientRegisterAddressRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientRegisterAddressRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ClientRegisterAddressRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

