// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

/**
 * <pre>
 *go客户端收到java服务端返回值
 * </pre>
 *
 * Protobuf type {@code server.ClientTransactionJavaRes}
 */
public  final class ClientTransactionJavaRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:server.ClientTransactionJavaRes)
    ClientTransactionJavaResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientTransactionJavaRes.newBuilder() to construct.
  private ClientTransactionJavaRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientTransactionJavaRes() {
    txidRes_ = "";
    isReceivedRes_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientTransactionJavaRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            txidRes_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            isReceivedRes_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return JavaTranscationServerProto.internal_static_server_ClientTransactionJavaRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return JavaTranscationServerProto.internal_static_server_ClientTransactionJavaRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ClientTransactionJavaRes.class, ClientTransactionJavaRes.Builder.class);
  }

  public static final int TXIDRES_FIELD_NUMBER = 1;
  private volatile java.lang.Object txidRes_;
  /**
   * <code>string TxidRes = 1;</code>
   */
  public java.lang.String getTxidRes() {
    java.lang.Object ref = txidRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txidRes_ = s;
      return s;
    }
  }
  /**
   * <code>string TxidRes = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTxidResBytes() {
    java.lang.Object ref = txidRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txidRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISRECEIVEDRES_FIELD_NUMBER = 2;
  private volatile java.lang.Object isReceivedRes_;
  /**
   * <code>string IsReceivedRes = 2;</code>
   */
  public java.lang.String getIsReceivedRes() {
    java.lang.Object ref = isReceivedRes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isReceivedRes_ = s;
      return s;
    }
  }
  /**
   * <code>string IsReceivedRes = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIsReceivedResBytes() {
    java.lang.Object ref = isReceivedRes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isReceivedRes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTxidResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txidRes_);
    }
    if (!getIsReceivedResBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isReceivedRes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTxidResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txidRes_);
    }
    if (!getIsReceivedResBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isReceivedRes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ClientTransactionJavaRes)) {
      return super.equals(obj);
    }
    ClientTransactionJavaRes other = (ClientTransactionJavaRes) obj;

    boolean result = true;
    result = result && getTxidRes()
        .equals(other.getTxidRes());
    result = result && getIsReceivedRes()
        .equals(other.getIsReceivedRes());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TXIDRES_FIELD_NUMBER;
    hash = (53 * hash) + getTxidRes().hashCode();
    hash = (37 * hash) + ISRECEIVEDRES_FIELD_NUMBER;
    hash = (53 * hash) + getIsReceivedRes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ClientTransactionJavaRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientTransactionJavaRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientTransactionJavaRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientTransactionJavaRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientTransactionJavaRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ClientTransactionJavaRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ClientTransactionJavaRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ClientTransactionJavaRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ClientTransactionJavaRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ClientTransactionJavaRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ClientTransactionJavaRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ClientTransactionJavaRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ClientTransactionJavaRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *go客户端收到java服务端返回值
   * </pre>
   *
   * Protobuf type {@code server.ClientTransactionJavaRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ClientTransactionJavaRes)
          ClientTransactionJavaResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JavaTranscationServerProto.internal_static_server_ClientTransactionJavaRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JavaTranscationServerProto.internal_static_server_ClientTransactionJavaRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientTransactionJavaRes.class, ClientTransactionJavaRes.Builder.class);
    }

    // Construct using serverproto.ClientTransactionJavaRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      txidRes_ = "";

      isReceivedRes_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return JavaTranscationServerProto.internal_static_server_ClientTransactionJavaRes_descriptor;
    }

    @java.lang.Override
    public ClientTransactionJavaRes getDefaultInstanceForType() {
      return ClientTransactionJavaRes.getDefaultInstance();
    }

    @java.lang.Override
    public ClientTransactionJavaRes build() {
      ClientTransactionJavaRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ClientTransactionJavaRes buildPartial() {
      ClientTransactionJavaRes result = new ClientTransactionJavaRes(this);
      result.txidRes_ = txidRes_;
      result.isReceivedRes_ = isReceivedRes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ClientTransactionJavaRes) {
        return mergeFrom((ClientTransactionJavaRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ClientTransactionJavaRes other) {
      if (other == ClientTransactionJavaRes.getDefaultInstance()) return this;
      if (!other.getTxidRes().isEmpty()) {
        txidRes_ = other.txidRes_;
        onChanged();
      }
      if (!other.getIsReceivedRes().isEmpty()) {
        isReceivedRes_ = other.isReceivedRes_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ClientTransactionJavaRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ClientTransactionJavaRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object txidRes_ = "";
    /**
     * <code>string TxidRes = 1;</code>
     */
    public java.lang.String getTxidRes() {
      java.lang.Object ref = txidRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txidRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTxidResBytes() {
      java.lang.Object ref = txidRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txidRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public Builder setTxidRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      txidRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public Builder clearTxidRes() {
      
      txidRes_ = getDefaultInstance().getTxidRes();
      onChanged();
      return this;
    }
    /**
     * <code>string TxidRes = 1;</code>
     */
    public Builder setTxidResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      txidRes_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object isReceivedRes_ = "";
    /**
     * <code>string IsReceivedRes = 2;</code>
     */
    public java.lang.String getIsReceivedRes() {
      java.lang.Object ref = isReceivedRes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isReceivedRes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string IsReceivedRes = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIsReceivedResBytes() {
      java.lang.Object ref = isReceivedRes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isReceivedRes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string IsReceivedRes = 2;</code>
     */
    public Builder setIsReceivedRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      isReceivedRes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string IsReceivedRes = 2;</code>
     */
    public Builder clearIsReceivedRes() {
      
      isReceivedRes_ = getDefaultInstance().getIsReceivedRes();
      onChanged();
      return this;
    }
    /**
     * <code>string IsReceivedRes = 2;</code>
     */
    public Builder setIsReceivedResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      isReceivedRes_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:server.ClientTransactionJavaRes)
  }

  // @@protoc_insertion_point(class_scope:server.ClientTransactionJavaRes)
  private static final ClientTransactionJavaRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ClientTransactionJavaRes();
  }

  public static ClientTransactionJavaRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientTransactionJavaRes>
      PARSER = new com.google.protobuf.AbstractParser<ClientTransactionJavaRes>() {
    @java.lang.Override
    public ClientTransactionJavaRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientTransactionJavaRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientTransactionJavaRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientTransactionJavaRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ClientTransactionJavaRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

