// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventServer.proto

package serverproto.serverproto;

public final class JavaTranscationServerProto {
  private JavaTranscationServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ClientRegisterAddressReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ClientRegisterAddressReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ClientRegisterAddressRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ClientRegisterAddressRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ClientTransactionReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ClientTransactionReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ClientTransactionRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ClientTransactionRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ChainTranscationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ChainTranscationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ChainTranscationReq_TxsReqEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ChainTranscationReq_TxsReqEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ChainTranscationRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ChainTranscationRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ClientTransactionJavaReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ClientTransactionJavaReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_ClientTransactionJavaRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_ClientTransactionJavaRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021eventServer.proto\022\006server\"[\n\030ClientReg" +
      "isterAddressReq\022\024\n\014AddRessIpReq\030\001 \001(\t\022\026\n" +
      "\016AddRessPortReq\030\002 \001(\t\022\021\n\tRemarkReq\030\003 \001(\t" +
      "\"W\n\030ClientRegisterAddressRes\022\022\n\nMessageR" +
      "es\030\001 \001(\t\022\021\n\tIsSuccess\030\002 \001(\010\022\024\n\014MessageID" +
      "Res\030\003 \001(\t\"\'\n\024ClientTransactionReq\022\017\n\007Txi" +
      "dReq\030\001 \001(\t\"L\n\024ClientTransactionRes\022\017\n\007Tx" +
      "idRes\030\001 \001(\t\022\017\n\007CodeRes\030\002 \001(\t\022\022\n\nMessageR" +
      "es\030\003 \001(\t\"\221\001\n\023ChainTranscationReq\022\022\n\nBatc" +
      "hidReq\030\001 \001(\t\0227\n\006TxsReq\030\002 \003(\0132\'.server.Ch" +
      "ainTranscationReq.TxsReqEntry\032-\n\013TxsReqE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"<\n\023" +
      "ChainTranscationRes\022\022\n\nBatchidReq\030\001 \001(\t\022" +
      "\021\n\tIsSuccess\030\002 \001(\010\"P\n\030ClientTransactionJ" +
      "avaReq\022\017\n\007TxidRes\030\001 \001(\t\022\017\n\007CodeRes\030\002 \001(\t" +
      "\022\022\n\nMessageRes\030\003 \001(\t\"B\n\030ClientTransactio" +
      "nJavaRes\022\017\n\007TxidRes\030\001 \001(\t\022\025\n\rIsReceivedR" +
      "es\030\002 \001(\t2\232\002\n\016GoEventService\022[\n\023GoClientR" +
      "egistEvent\022 .server.ClientRegisterAddres" +
      "sReq\032 .server.ClientRegisterAddressRes\"\000" +
      "\022T\n\024GoClientRequestEvent\022\034.server.Client" +
      "TransactionReq\032\034.server.ClientTransactio" +
      "nRes\"\000\022U\n\023GoChainRequestEvent\022\033.server.C" +
      "hainTranscationReq\032\033.server.ChainTransca" +
      "tionRes\"\000(\0010\0012v\n\020JavaEventService\022b\n\026Jav" +
      "aClientRequestEvent\022 .server.ClientTrans" +
      "actionJavaReq\032 .server.ClientTransaction" +
      "JavaRes\"\000(\0010\001B8\n\013serverprotoB\032JavaTransc" +
      "ationServerProtoP\001Z\013serverprotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_ClientRegisterAddressReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_ClientRegisterAddressReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ClientRegisterAddressReq_descriptor,
        new java.lang.String[] { "AddRessIpReq", "AddRessPortReq", "RemarkReq", });
    internal_static_server_ClientRegisterAddressRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_ClientRegisterAddressRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ClientRegisterAddressRes_descriptor,
        new java.lang.String[] { "MessageRes", "IsSuccess", "MessageIDRes", });
    internal_static_server_ClientTransactionReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_server_ClientTransactionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ClientTransactionReq_descriptor,
        new java.lang.String[] { "TxidReq", });
    internal_static_server_ClientTransactionRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_server_ClientTransactionRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ClientTransactionRes_descriptor,
        new java.lang.String[] { "TxidRes", "CodeRes", "MessageRes", });
    internal_static_server_ChainTranscationReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_server_ChainTranscationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ChainTranscationReq_descriptor,
        new java.lang.String[] { "BatchidReq", "TxsReq", });
    internal_static_server_ChainTranscationReq_TxsReqEntry_descriptor =
      internal_static_server_ChainTranscationReq_descriptor.getNestedTypes().get(0);
    internal_static_server_ChainTranscationReq_TxsReqEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ChainTranscationReq_TxsReqEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_server_ChainTranscationRes_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_server_ChainTranscationRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ChainTranscationRes_descriptor,
        new java.lang.String[] { "BatchidReq", "IsSuccess", });
    internal_static_server_ClientTransactionJavaReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_server_ClientTransactionJavaReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ClientTransactionJavaReq_descriptor,
        new java.lang.String[] { "TxidRes", "CodeRes", "MessageRes", });
    internal_static_server_ClientTransactionJavaRes_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_server_ClientTransactionJavaRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_ClientTransactionJavaRes_descriptor,
        new java.lang.String[] { "TxidRes", "IsReceivedRes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
